#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
#  FlowerOS FOTD Builder (bash)
#  FOTD = Flower Of The Day
#  Pre-renders PNG source images from motd/Import/ into xterm-256 .ascii
#  files at multiple sizes using the native png2term C binary.
#
#  Fallback: uses bash/Python image tools if png2term is not built.
#
#  Usage:  ./build-motd.sh
#  Build png2term first:
#    gcc -O2 -std=c11 -Wall -Wextra -o png2term src/utils/png2term.c -lm -lz
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMPORT_DIR="$SCRIPT_DIR/motd/Import"
OUTPUT_DIR="$SCRIPT_DIR/motd/ascii-output"
CACHE_DIR="$SCRIPT_DIR/motd/cache"
IMAGE_TOOLS="$SCRIPT_DIR/features/v1.2/visual-experience/image-tools"

mkdir -p "$IMPORT_DIR" "$OUTPUT_DIR" "$CACHE_DIR"

# ── Colour helpers ────────────────────────────────────────────────────────
c=$'\033[36m' g=$'\033[32m' y=$'\033[33m' r=$'\033[31m' m=$'\033[35m' z=$'\033[0m'
ok()   { echo "  ${g}✓${z} $*"; }
warn() { echo "  ${y}⚠${z} $*"; }
info() { echo "  ${c}→${z} $*"; }

echo ""
echo "${m}╔══════════════════════════════════════════════════════════════════════════╗${z}"
echo "${m}║     🌸 FlowerOS FOTD Builder v1.2.0 🌸                                  ║${z}"
echo "${m}╚══════════════════════════════════════════════════════════════════════════╝${z}"
echo ""

# ── Detect png2term ──────────────────────────────────────────────────────
PNG2TERM=""
if command -v png2term >/dev/null 2>&1; then
    PNG2TERM="png2term"
elif [[ -x "$SCRIPT_DIR/png2term" ]]; then
    PNG2TERM="$SCRIPT_DIR/png2term"
fi

if [[ -n "$PNG2TERM" ]]; then
    ok "Using native png2term: $PNG2TERM"
else
    warn "png2term not found — falling back to bash/Python tools"
    echo "     Build it: gcc -O2 -std=c11 -Wall -Wextra -o png2term src/utils/png2term.c -lm -lz"
fi

# ── Scan for images ──────────────────────────────────────────────────────
shopt -s nullglob
images=( "$IMPORT_DIR"/*.png "$IMPORT_DIR"/*.jpg "$IMPORT_DIR"/*.jpeg "$IMPORT_DIR"/*.bmp )
shopt -u nullglob

if [[ ${#images[@]} -eq 0 ]]; then
    warn "No images found in $IMPORT_DIR"
    echo ""
    echo "  Add images to motd/Import/ and run again."
    echo "  Supported: PNG, JPG, JPEG, BMP"
    echo ""
    exit 0
fi

ok "Found ${#images[@]} image(s)"

# ── Render each image at multiple sizes ──────────────────────────────────
total=0

render_one() {
    local img="$1" cols="$2" pastel="$3" output="$4" label="$5"
    printf "  → %-24s" "$label"
    if [[ -n "$PNG2TERM" ]]; then
        if "$PNG2TERM" "$img" "$cols" "$pastel" > "$output" 2>/dev/null; then
            echo "${g}✓${z}"
            (( total++ )) || true
            return
        fi
    fi
    # Fallback: bash img2term.sh (requires Python + Pillow)
    if [[ -f "$IMAGE_TOOLS/img2term.sh" ]]; then
        if bash "$IMAGE_TOOLS/img2term.sh" "$img" "$cols" "$pastel" half > "$output" 2>/dev/null; then
            echo "${g}✓${z} (bash fallback)"
            (( total++ )) || true
            return
        fi
    fi
    echo "${r}✗${z}"
}

for img in "${images[@]}"; do
    name="$(basename "${img%.*}")"
    echo ""
    info "Processing: $(basename "$img")"

    render_one "$img"  60 0.55 "$OUTPUT_DIR/${name}-small.ascii"  "Small (60 cols)..."
    render_one "$img" 120 0.55 "$OUTPUT_DIR/${name}-medium.ascii" "Medium (120 cols)..."
    render_one "$img" 160 0.55 "$OUTPUT_DIR/${name}-large.ascii"  "Large (160 cols)..."
    render_one "$img" 120 0.40 "$OUTPUT_DIR/${name}-hash.ascii"   "Hash mode (120 cols)..."

    # ── Generate config script for this image ────────────────────────────
    cfg="$CACHE_DIR/${name}-config.sh"
    cat > "$cfg" <<EOF
#!/usr/bin/env bash
# FlowerOS MOTD Config — $name
# Auto-generated by build-motd.sh

FOTD_NAME="$name"
FOTD_SMALL="$OUTPUT_DIR/${name}-small.ascii"
FOTD_MEDIUM="$OUTPUT_DIR/${name}-medium.ascii"
FOTD_LARGE="$OUTPUT_DIR/${name}-large.ascii"
FOTD_HASH="$OUTPUT_DIR/${name}-hash.ascii"

show_fotd() {
    local width=\${COLUMNS:-120}
    if [[ \$width -lt 80 ]]; then
        [[ -f "\$FOTD_SMALL" ]] && cat "\$FOTD_SMALL"
    elif [[ \$width -lt 140 ]]; then
        [[ -f "\$FOTD_MEDIUM" ]] && cat "\$FOTD_MEDIUM"
    else
        [[ -f "\$FOTD_LARGE" ]] && cat "\$FOTD_LARGE"
    fi
}

export FOTD_NAME FOTD_SMALL FOTD_MEDIUM FOTD_LARGE FOTD_HASH
EOF
    chmod +x "$cfg"
done

# ── Summary ──────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ok "Generated $total FOTD art file(s) in $OUTPUT_DIR"
echo ""
echo "  ${c}Preview:${z}  cat motd/ascii-output/<name>-small.ascii"
echo "  ${c}FOTD use:${z} flower-motd.sh auto-detects motd/ascii-output/"
echo ""
echo "${m}🌺 FOTD build complete! 🌺${z}"
echo ""
