#!/usr/bin/env bash
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
#  FlowerOS MOTD - Iris Garden
#  Shows a blooming iris flower on login
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/banners.sh"

# Iris ASCII art (generated by flower_blossom.py)
IRIS_ART="${SCRIPT_DIR}/../ascii_out/beautiful-flowers-iris.ansi.txt"

if [[ -f "$IRIS_ART" ]]; then
    # Show first 20 lines of the iris (top of flower)
    head -n 20 "$IRIS_ART"
    echo ""
else
    # Fallback: simple flower emoji
    echo "     ðŸŒ¸"
    echo "    ðŸŒ¸ðŸŒ¸"
    echo "   ðŸŒ¸ðŸŒ¸ðŸŒ¸"
    echo ""
fi

fos_banner_title "FlowerOS v1.3.0" "The Universal Operating System" "ðŸŒº" "ðŸŒº"

echo -e "${_FOS_GREEN}Welcome to the Garden${_FOS_RESET}"
echo ""
echo -e "${_FOS_CYAN}Today's Bloom:${_FOS_RESET} Iris (Botanical Intelligence System)"
echo -e "${_FOS_DIM}  â€¢ GPU Batch Processing Active${_FOS_RESET}"
echo -e "${_FOS_DIM}  â€¢ Network Routing Ready${_FOS_RESET}"
echo -e "${_FOS_DIM}  â€¢ Terminal Unity Enabled${_FOS_RESET}"
echo ""

fos_tagline
