#!/usr/bin/env bash
# FlowerOS FOTD Config - 01
# FOTD = Flower Of The Day
# Auto-generated by build-motd.sh

FOTD_NAME="01"
FOTD_SMALL="/mnt/c/Users/Liam/Desktop/FlowerOS/motd/ascii-output/01-small.ascii"
FOTD_MEDIUM="/mnt/c/Users/Liam/Desktop/FlowerOS/motd/ascii-output/01-medium.ascii"
FOTD_LARGE="/mnt/c/Users/Liam/Desktop/FlowerOS/motd/ascii-output/01-large.ascii"
FOTD_HASH="/mnt/c/Users/Liam/Desktop/FlowerOS/motd/ascii-output/01-hash.ascii"

# Show FOTD based on terminal width
show_fotd() {
    local width=${COLUMNS:-120}

    if [[ $width -lt 80 ]]; then
        [[ -f "$FOTD_SMALL" ]] && cat "$FOTD_SMALL"
    elif [[ $width -lt 140 ]]; then
        [[ -f "$FOTD_MEDIUM" ]] && cat "$FOTD_MEDIUM"
    else
        [[ -f "$FOTD_LARGE" ]] && cat "$FOTD_LARGE"
    fi
}

# Export for use in other scripts
export FOTD_NAME FOTD_SMALL FOTD_MEDIUM FOTD_LARGE FOTD_HASH
