#!/usr/bin/env bash
# FlowerOS MOTD Config - 02
# Auto-generated by build-motd.sh

MOTD_NAME="02"
MOTD_SMALL="/mnt/c/Users/Liam/Desktop/FlowerOS/motd/ascii-output/02-small.ascii"
MOTD_MEDIUM="/mnt/c/Users/Liam/Desktop/FlowerOS/motd/ascii-output/02-medium.ascii"
MOTD_LARGE="/mnt/c/Users/Liam/Desktop/FlowerOS/motd/ascii-output/02-large.ascii"
MOTD_HASH="/mnt/c/Users/Liam/Desktop/FlowerOS/motd/ascii-output/02-hash.ascii"

# Show MOTD based on terminal width
show_motd() {
    local width=${COLUMNS:-120}
    
    if [[ $width -lt 80 ]]; then
        [[ -f "$MOTD_SMALL" ]] && cat "$MOTD_SMALL"
    elif [[ $width -lt 140 ]]; then
        [[ -f "$MOTD_MEDIUM" ]] && cat "$MOTD_MEDIUM"
    else
        [[ -f "$MOTD_LARGE" ]] && cat "$MOTD_LARGE"
    fi
}

# Export for use in other scripts
export MOTD_NAME MOTD_SMALL MOTD_MEDIUM MOTD_LARGE MOTD_HASH
