"""
floweros.motd._data
~~~~~~~~~~~~~~~~~~~
Curated local corpus: elements, chemicals, plants.
No network, no dependencies.  Imported by provider_random.py.
Each pool entry is a (display_name, detail_tag, blurb) triple.
"""

ELEMENTS = [
    ("Hydrogen",    "Z=1",   "Lightest element; main fuel of stars."),
    ("Helium",      "Z=2",   "Inert noble gas; superfluid below 2.17 K."),
    ("Lithium",     "Z=3",   "Lightest metal; key to rechargeable batteries."),
    ("Carbon",      "Z=6",   "Backbone of organic chemistry and many materials."),
    ("Oxygen",      "Z=8",   "Essential for aerobic life; most abundant in Earth's crust."),
    ("Silicon",     "Z=14",  "Semiconductor basis; second most abundant crustal element."),
    ("Phosphorus",  "Z=15",  "Essential to DNA, RNA, and ATP; reactive allotropes."),
    ("Sulfur",      "Z=16",  "Solid non-metal; key role in proteins and vulcanisation."),
    ("Iron",        "Z=26",  "Common structural metal; core of terrestrial planets."),
    ("Copper",      "Z=29",  "Excellent conductor; antimicrobial surface properties."),
    ("Gallium",     "Z=31",  "Melts near room temperature; used in semiconductors."),
    ("Arsenic",     "Z=33",  "Metalloid; historic poison, now in semiconductors."),
    ("Bromine",     "Z=35",  "One of only two liquid elements at room temperature."),
    ("Silver",      "Z=47",  "Highest electrical conductivity of any element."),
    ("Tin",         "Z=50",  "Corrosion-resistant; critical to solder and alloys."),
    ("Iodine",      "Z=53",  "Essential trace element; antiseptic and thyroid-critical."),
    ("Tungsten",    "Z=74",  "Highest melting point of all metals: 3422 °C."),
    ("Gold",        "Z=79",  "Noble metal; excellent conductor, corrosion-resistant."),
    ("Mercury",     "Z=80",  "Only metal liquid at room temperature; highly toxic."),
    ("Radium",      "Z=88",  "Radioactive alkaline earth; early cancer therapy use."),
    ("Uranium",     "Z=92",  "Actinide used in fission; dense and radioactive."),
    ("Plutonium",   "Z=94",  "Synthetic actinide; critical mass as small as 10 kg."),
    ("Neodymium",   "Z=60",  "Rare-earth used in the strongest permanent magnets."),
    ("Osmium",      "Z=76",  "Densest naturally occurring element: 22.59 g/cm³."),
    ("Francium",    "Z=87",  "Most unstable naturally occurring element; highly reactive."),
    ("Astatine",    "Z=85",  "Rarest naturally occurring element on Earth's crust."),
]

CHEMICALS = [
    ("Sodium chloride",        "NaCl",         "Ionic solid; classic face-centred cubic lattice."),
    ("Ammonia",                "NH₃",          "Trigonal pyramidal; important industrial feedstock."),
    ("Sulfuric acid",          "H₂SO₄",        "Most industrially produced chemical worldwide."),
    ("Ethanol",                "C₂H₅OH",       "Polar protic solvent; miscible with water in all ratios."),
    ("Carbon dioxide",         "CO₂",          "Linear molecule; greenhouse gas and dry ice."),
    ("Acetylsalicylic acid",   "C₉H₈O₄",       "Aspirin; anti-inflammatory analgesic synthesised 1897."),
    ("Caffeine",               "C₈H₁₀N₄O₂",   "Purine alkaloid; adenosine receptor antagonist."),
    ("Methane",                "CH₄",          "Simplest alkane; potent greenhouse gas (GWP ≈ 27×CO₂)."),
    ("Water",                  "H₂O",          "Universal solvent; density maximum at 4 °C."),
    ("Glucose",                "C₆H₁₂O₆",     "Primary cellular fuel; product of photosynthesis."),
    ("Nitric acid",            "HNO₃",         "Strong oxidising acid; key feedstock for fertilisers."),
    ("Acetic acid",            "CH₃COOH",      "Weak acid; active component of vinegar."),
    ("Ozone",                  "O₃",           "Allotrope of oxygen; UV shield in stratosphere."),
    ("Ethylene",               "C₂H₄",         "Simplest alkene; most produced organic compound."),
    ("Benzene",                "C₆H₆",         "Archetypical aromatic ring; carcinogenic solvent."),
    ("Acetone",                "C₃H₆O",        "Ketone solvent; fully miscible with water."),
    ("Hydrogen peroxide",      "H₂O₂",         "Unstable oxidant; decomposes to water and oxygen."),
    ("Urea",                   "CO(NH₂)₂",     "First organic compound synthesised from inorganic precursors (1828)."),
    ("Cholesterol",            "C₂₇H₄₆O",      "Sterol lipid; essential to cell membranes and hormones."),
    ("Capsaicin",              "C₁₈H₂₇NO₃",   "Pungent alkaloid in chillies; binds TRPV1 receptors."),
    ("Methamphetamine",        "C₁₀H₁₅N",      "CNS stimulant; potent dopamine-releasing agent."),
    ("Penicillin G",           "C₁₆H₁₈N₂O₄S", "First beta-lactam antibiotic; discovered by Fleming 1928."),
    ("Chlorophyll a",          "C₅₅H₇₂MgN₄O₅","Light-absorbing pigment; core of oxygenic photosynthesis."),
    ("ATP",                    "C₁₀H₁₆N₅O₁₃P₃","Universal cellular energy currency."),
    ("Silicon dioxide",        "SiO₂",         "Most abundant mineral in Earth's crust; glass precursor."),
]

PLANTS = [
    ("Lavender",        "Lavandula",              "Aromatic; drought-tolerant; repels insects."),
    ("Sunflower",       "Helianthus annuus",      "Large inflorescence; exhibits heliotropism."),
    ("Aloe vera",       "Aloe barbadensis",       "Succulent; gel used topically for burns."),
    ("Rosemary",        "Salvia rosmarinus",      "Hardy culinary herb; rich in camphor oil."),
    ("Bamboo",          "Bambusoideae",           "Fastest-growing plant; up to 91 cm/day."),
    ("Sequoia",         "Sequoiadendron giganteum","Largest living organisms by volume."),
    ("Venus flytrap",   "Dionaea muscipula",      "Carnivorous; snap-trap closes in ~100 ms."),
    ("Baobab",          "Adansonia",              "Stores >100,000 L of water; lives 3,000+ years."),
    ("Corpse flower",   "Amorphophallus titanum", "Largest unbranched inflorescence; thermogenic."),
    ("Rafflesia",       "Rafflesia arnoldii",     "Largest individual flower; no leaves or stems."),
    ("Welwitschia",     "Welwitschia mirabilis",  "Only two leaves, grows for 2,000+ years."),
    ("Mangrove",        "Rhizophora",             "Halophyte; roots exclude up to 97% of salt."),
    ("Pitcher plant",   "Nepenthes",              "Carnivorous; pitfall trap digests arthropods."),
    ("Opium poppy",     "Papaver somniferum",     "Source of morphine, codeine, and heroin."),
    ("Quinine tree",    "Cinchona officinalis",   "Bark yields quinine; first antimalarial treatment."),
    ("Ginkgo",          "Ginkgo biloba",          "Living fossil; unchanged for 200 million years."),
    ("Mimosa",          "Mimosa pudica",          "Thigmonastic response; folds leaves on touch."),
    ("Strangler fig",   "Ficus",                  "Epiphyte that engulfs and kills host trees."),
    ("Sea grass",       "Posidonia oceanica",     "Clone meadows can be 100,000 years old."),
    ("Black lotus",     "Nelumbo nucifera",       "Sacred in multiple religions; seeds viable 1,300 years."),
    ("Creosote bush",   "Larrea tridentata",      "King Clone ring estimated at ~11,700 years old."),
    ("Foxglove",        "Digitalis purpurea",     "Source of digoxin; treats heart conditions."),
    ("Wisteria",        "Wisteria sinensis",      "Woody twiner; individual specimens weigh over 100 tonnes."),
]
